// CG lifecycle, fixed designs and old-save compatibility, inside the game closure.
const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path');
let checks = 0;
const check = (ok, why) => { assert.ok(ok, why); checks++; };
newGame(); state = 'game';
const siblings = W.flags.prologueKids.map(C);
check(siblings.map(c => catLook(c).coat).join('|') === '狸花白|狸花白|橘猫', 'All opening siblings have their fixed coats');
check(siblings.map(characterArtKey).join('|') === 'li1|li2|li3', 'Opening siblings have stable identities');
const coatSignature = c => { const l=catLook(c); return JSON.stringify([l.coat,l.wz,l.eyeL,l.eyeR,l.main,l.second,l.seed2,l.tabbyType]); };
const firstLooks = siblings.map(coatSignature);
newGame(); state = 'game';
check(W.flags.prologueKids.map(C).every((c,i) => coatSignature(c) === firstLooks[i]), 'Coats and markings match across restarts');
// Aptitude scores remain random; only inspect coat-related appearance fields in later random-seed runs.
const snapshot = JSON.stringify(W); saveGame();
let pre = 0, fx = 0, post = 0;
showEvent({ title: '测试三问', text: '保留原事件。', pre: () => pre++, post: () => post++, opts: [opt('继续', '', () => fx++)] }, 'prologue');
check(top().type === 'cg' && MODAL[MODAL.length-2].type === 'event', 'CG sits above the actual event');
check(pre === 1 && fx === 0 && post === 0 && holding(), 'CG pauses before choices, pre runs once');
check(!saveGame() && localStorage.getItem(SAVE+'w') === snapshot, 'Pending CG cannot overwrite the last complete save');
drop(top()); choose(top(), top().e.opts[0]);
check(fx === 1 && post === 1 && pre === 1, 'Dismissing CG preserves exactly one execution of all callbacks');
const afterChoice = JSON.stringify(W);
openCG('prologue'); check(top().type === 'cg' && top().replay, 'Seen CG can be replayed'); drop(top());
check(JSON.stringify(W) === afterChoice && fx === 1 && post === 1, 'Replaying CG changes no story state or rewards');
showEvent({title:'重复', text:'已解锁', opts:[]},'prologue');
check(top().type === 'event', 'Duplicate event does not replay CG automatically'); MODAL.length=0;
const seen = JSON.stringify(W.art.seen); SAVE_SUSPENDED++; showEvent({title:'跨年', text:'模拟', opts:[]},'siege'); SAVE_SUSPENDED--;
check(top().type === 'event' && JSON.stringify(W.art.seen) === seen, 'Scenario catch-up does not unlock unseen scenes'); MODAL.length=0;
const expectedGene = JSON.stringify(C('zhaoji').g);
const z = mkc({ id:'zheng', name:'政', born:W.t, mom:'zhaoji', dad:'yiren', bio:'lv', hist:true, g:breed(C('zhaoji').g,C('lv').g,Math.random,'M') });
check(catLook(z).coat === '狸花白' && z.bio === 'lv', 'Zheng has an inherited mixed coat and Lu as biological father');
check(checkParentage(z,C('zhaoji'),C('yiren')).lvl === 3, 'Stripes and white reveal impossible legal parentage on Zhao Ji route');
check(checkParentage(z,C('zhaoji'),C('lv')).lvl === 0, 'Actual biological parents explain the coat');
check(catLook(z).wz.join('|') === 'chin|muzzle', 'Zheng has limited muzzle/chin white, not the parent blaze');
check(JSON.stringify(C('zhaoji').g) === expectedGene, 'Fixing a child does not rewrite its mother');
check(characterArtKey(z) === 'zheng-baby', 'Newborn uses baby illustration');
check(storyCGFor('zhengborn', {}) === 'zheng-zhao', 'Zhao Ji birth scene selected');
check(storyCGFor('born', EV.zhengborn()) === 'zheng-zhao', 'The real born queue event resolves to Zheng birth artwork');
z.mom = W.flags.prologueKids[1];
check(storyCGFor('zhengborn', {}) === 'zheng-li', 'Second Li sibling birth scene selected');
z.mom = W.flags.prologueKids[0];
check(storyCGFor('zhengborn', {}) === null, 'Unsupported old family branch does not show the wrong mother');
W.t = 13*4; check(characterArtKey(z) === 'zheng-young', 'Young Zheng has a child portrait');
W.t = 22*4; check(characterArtKey(z) === 'zheng', 'Adult Zheng uses the king portrait');
W.kingId = W.player;
check(storyCGFor('a3_jingke',{}) === null && storyCGFor('guanli',{}) === null, 'A usurper is not illustrated as Zheng');
W.kingId='zheng';
check(storyCGFor('qingsuan',{title:'假父'}) === null, 'Lao Ai branch does not show Zheng judgment');
// Old save appearances are retained, while optional art state is repaired and bounded.
const old = JSON.parse(afterChoice); delete old.art;
for (const id of old.flags.prologueKids) delete old.chars[id].flags.artIdentity;
const beforeGenes = JSON.stringify(Object.values(old.chars).map(c=>c.g));
const migrated = prepareWorld(decodeSave(JSON.stringify(old)));
check(JSON.stringify(Object.values(migrated.chars).map(c=>c.g)) === beforeGenes, 'Legacy appearance genes and descendants are not rewritten');
check(Object.keys(migrated.art.seen).length === 0, 'Legacy saves do not gain unseen spoilers');
W.art = {seen:{prologue:{t:0,title:'三问'}, siege:{t:999999}, unknown:{t:0}}}; artDefaults();
check(Object.keys(W.art.seen).join() === 'prologue', 'Unknown and future gallery entries are discarded');
for (const id of Object.keys(ART_CAST)) for (const folder of ['portraits','faces']) check(fs.existsSync(path.join('art',folder,id+'.webp')), 'Missing '+folder+'/'+id);
for (const id of Object.keys(STORY_CG)) check(fs.existsSync(path.join('art','cg',id+'.webp')), 'Missing CG '+id);
// Exercise both real birth paths, not only isolated character creation.
newGame(); state='game'; zhaojiWed(); check(C('zhaoji').preg.f === 'lv','Historical default uses Lu when no conception exists');
giveBirth(C('zhaoji')); const zhaoLook=coatSignature(C('zheng'));
check(C('zheng').bio==='lv' && C('zheng').dad==='yiren','Birth keeps biological and legal father distinct');
check(W.secrets.some(s=>s.kid==='zheng'),'Zhao route creates a discoverable secret');
for(const locus of Object.keys(ALLELES).concat(['W'])) check(C('lv').g[locus].includes(C('zheng').g[locus][0]) && C('zhaoji').g[locus].includes(C('zheng').g[locus][1]),'Zhao cross inherits legal alleles: '+locus);
newGame(); state='game'; const liMom=C(W.flags.prologueKids[1]); liBrideWed(liMom); giveBirth(liMom);
check(C('zheng').bio==='yiren' && C('zheng').mom===liMom.id,'Li route can be the legitimate son of Yiren');
check(coatSignature(C('zheng'))===zhaoLook,'Both parent pairs produce the same visible coat');
check(checkParentage(C('zheng'),liMom,C('yiren')).lvl===0,'Li route carries no false parentage clue');
for(const locus of Object.keys(ALLELES).concat(['W'])) check(C('yiren').g[locus].includes(C('zheng').g[locus][0]) && liMom.g[locus].includes(C('zheng').g[locus][1]),'Li cross inherits legal alleles: '+locus);
const legacyZ=C('zheng'); delete legacyZ.flags.artDesign; check(characterArtKey(legacyZ)==='zheng-baby','Player-related legacy Zheng also uses the existing illustration');
// A real conception must survive the historical marriage; artwork must not rewrite player genes.
newGame(); state='game';
const loverMom=C('zhaoji'); setPreg(loverMom,W.player); const conception=JSON.parse(JSON.stringify(loverMom.preg));
zhaojiWed();
for(const k of ['f','sp','due']) check(loverMom.preg[k]===conception[k],'Marriage preserves conception field '+k);
const originalBreed=breed; let bornGenome;
breed=(...args)=>{ const g=originalBreed(...args); bornGenome=JSON.stringify(g); return g; };
try { giveBirth(loverMom); } finally { breed=originalBreed; }
const playerZ=C('zheng');
check(playerZ.bio===W.player && playerZ.dad==='yiren','Player remains biological father of Yiren household Zheng');
assert.deepEqual(JSON.parse(JSON.stringify(playerZ.g)),JSON.parse(bornGenome),'Existing Zheng illustration never replaces player-inherited genes'); checks++;
check(characterArtKey(playerZ)==='zheng-baby' && storyCGFor('zhengborn',{})==='zheng-zhao','Player-related Zheng uses existing portrait and birth CG');
check(W.secrets.some(s=>s.kid==='zheng'),'Player fatherhood remains a discoverable secret');
// Fallback cannot invent another birth over a pregnancy that already has a real father.
newGame(); state='game'; marry(C('zhaoji'),C('yiren')); setPreg(C('zhaoji'),W.player); W.t=12;
const fallbackDue=C('zhaoji').preg.due; ensureZheng();
check(!C('zheng') && C('zhaoji').preg.f===W.player && C('zhaoji').preg.due===fallbackDue,'Fallback waits for the real pregnancy');
giveBirth(C('zhaoji')); check(C('zheng').bio===W.player,'Fallback pregnancy keeps player fatherhood at birth');
// Married-to-player Zhao Ji has ordinary children, not a forced historical heir.
newGame(); state='game'; const wife=C('zhaoji'); marry(wife,P()); setPreg(wife,W.player);
const ordinaryPreg=JSON.stringify(wife.preg); W.t=12;
check(EV.meiji()===null,'Historical bride event does not take the player wife');
zhaojiWed(); ensureZheng();
check(wife.sp===W.player && JSON.stringify(wife.preg)===ordinaryPreg && !C('zheng'),'Marriage and fallback leave the player family untouched');
const priorKids=new Set(wife.kids); giveBirth(wife);
const ordinaryKids=wife.kids.filter(id=>!priorKids.has(id)).map(C);
check(ordinaryKids.length>0 && ordinaryKids.every(c=>c.id!=='zheng' && !c.hist && c.bio===W.player && c.dad===W.player && !characterArtKey(c)),'Player marriage produces ordinary children with ordinary portraits');
ensureZheng(); check(!C('zheng') && wife.sp===W.player,'Fallback also leaves the family alone after delivery');
console.log('PASS: '+checks+' art checks; fixed fur, CG callbacks/save/replay, branch matching, legacy saves, asset coverage.');
